# Data Science Numpy & CSV's

## Tasks Today:

1) <b>Numpy</b> <br>
 &nbsp;&nbsp;&nbsp;&nbsp; a) Python List Comparison <br>
 &nbsp;&nbsp;&nbsp;&nbsp; b) In-Class Exercise #1 <br>
 &nbsp;&nbsp;&nbsp;&nbsp; c) Importing <br>
 &nbsp;&nbsp;&nbsp;&nbsp; d) Creating an NDArray <br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - np.array() <br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - np.zeros() <br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - np.ones() <br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - np.arange() <br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - Making Lists into NDArrays <br>
 &nbsp;&nbsp;&nbsp;&nbsp; e) Performing Calculations on NDArrays <br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - Summation <br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - Difference <br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - Multiplication <br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - Division <br>
 &nbsp;&nbsp;&nbsp;&nbsp; f) Numpy Subsetting <br>
 &nbsp;&nbsp;&nbsp;&nbsp; g) Multi-dimensional Arrays <br>
 &nbsp;&nbsp;&nbsp;&nbsp; h) Indexing NDArrays <br>
 &nbsp;&nbsp;&nbsp;&nbsp; i) Checking NDArray Type <br>
 &nbsp;&nbsp;&nbsp;&nbsp; j) Altering NDArray Type <br>
 &nbsp;&nbsp;&nbsp;&nbsp; k) Checking the Shape <br>
 &nbsp;&nbsp;&nbsp;&nbsp; l) Altering the Shape <br>
 &nbsp;&nbsp;&nbsp;&nbsp; m) In-Class Exercise #2 <br>
 &nbsp;&nbsp;&nbsp;&nbsp; n) Complex Indexing & Assigning <br>
 &nbsp;&nbsp;&nbsp;&nbsp; o) Elementwise Multplication <br>
 &nbsp;&nbsp;&nbsp;&nbsp; p) np.where() <br>
 &nbsp;&nbsp;&nbsp;&nbsp; q) Random Sampling <br>

2) <b>Working With CSV's</b> <br>
 &nbsp;&nbsp;&nbsp;&nbsp; a) Imports <br>
 &nbsp;&nbsp;&nbsp;&nbsp; b) Reading a CSV <br>
 &nbsp;&nbsp;&nbsp;&nbsp; c) Loading a CSV's Data <br>
 &nbsp;&nbsp;&nbsp;&nbsp; d) Checking Number of Records <br>
 
3) <b>Exercises</b> <br>
 &nbsp;&nbsp;&nbsp;&nbsp; a) #1 - Calculate BMI with NDArrays <br>
 &nbsp;&nbsp;&nbsp;&nbsp; b) #2 - Find the Average Sum of Marathon Runners <br>
 &nbsp;&nbsp;&nbsp;&nbsp; c) #3 - Random Matrix Function <br>
 &nbsp;&nbsp;&nbsp;&nbsp; d) #4 - Comparing Boston Red Sox Hitting Numbers <br>

## Numpy <br>

<p>NumPy is a library for the Python programming language, adding support for large, multi-dimensional arrays and matrices, along with a large collection of high-level mathematical functions to operate on these arrays.</p>
<ul>
    <li>Shape = Rows & Columns</li>
    <li>Matrix = Entire Array</li>
    <li>Vector = Variables to be applied (same vector as the one used in physics)</li>
    <li>Array = Similar to lists</li>
</ul>

#### Python List Comparison

<p>Lists are flexible, dynamic python objects that do their job quite well. But they do not support some mathematical operations in an intuitive way. Consider the summation of two lists, $l_1$ and $l_2$</p>

In [2]:
# create two lists and sum both of them together (results may not be what you expect)
l_1 =[1,2,3]
l_2 =[4,5,6]

print(f"Summation of a regular pyton list: {l_1 + l_2}")
print(f"Difference of a regular pyhton list: {l_1 + l_2}")



Summation of a regular pyton list: [1, 2, 3, 4, 5, 6]


<p>If we wanted to sum lists elementwise, we could write our own function that does the job entirely within the framework of python</p>

#### In-Class Exercise #1 - Write a function that sums the indexes of two lists <br>
<p>Ex: [2, 3, 4] + [1, 5, 2] = [3, 8, 6]</p>

In [12]:
def lists_sum(l_1, l_2):
    output=[]
    for idx in range(len(l_1)):
        print (l_1[idx], l_2[idx])
        output.append(l_1[idx] + l_2[idx])
    return output
        
        
lists_sum([2,3,4],[1,5,2])
    

2 1
3 5
4 2


[3, 8, 6]

#### Importing

In [13]:
# always import as np, standard across all of data science
# pip install numpy
import numpy as np

In [14]:
np

<module 'numpy' from '/Users/Allison/opt/anaconda3/lib/python3.9/site-packages/numpy/__init__.py'>

#### Creating an NDArray <br>
<p>NumPy is based around a class called the $\textit{NDArray}$, which is a flexible vector / matrix class that implements the intuitive matrix and vector arithmatic lacking in basic Python. Let's start by creating some NDArrays:</p>

###### - np.array()

In [15]:
arr1 = np.array([5,10,15])
arr1

array([ 5, 10, 15])

In [16]:
print(type(arr1))

<class 'numpy.ndarray'>


###### - np.zeros()

In [17]:
# Shape -- np.zeros() has a parameter of "shape" that must be given (num_rows, num_columns)
arr_zeros = np.zeros(5)
arr_zeros


array([0., 0., 0., 0., 0.])

###### - np.ones()

In [19]:
arr_ones = np.ones((2,4),int) #without the int the numbers will automaticall be a float
arr_ones 

# notice no dots after the numbers, because we specified the datatype to be integer

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

###### - np.arange()

In [20]:
list(range(10,20, 2))


[10, 12, 14, 16, 18]

In [21]:
arr_range = np.arange(10,20,2)
arr_range

array([10, 12, 14, 16, 18])

###### - Making Lists into NDArrays

In [22]:
my_list = [1,5,8,9,34,45,63]
arr_list = np.array(my_list)
arr_list

array([ 1,  5,  8,  9, 34, 45, 63])

#### Performing Calculations on NDArrays

###### - Summation

In [25]:
arr_list1 = np.array([5,10,15,20,25])
arr_list2 = np.array([10,20,30,40,50])

result_sum =  arr_list2 + arr_list2
result_sum


array([ 20,  40,  60,  80, 100])

###### - Difference

In [26]:
result_difference = arr_list1 -arr_list2
result_difference

array([ -5, -10, -15, -20, -25])

###### - Multiplication

In [28]:
result_prod = arr_list1 * arr_list2
result_prod

array([  50,  200,  450,  800, 1250])

###### - Division

In [ ]:
result_div = arr_list1 / arr_list2
result_div

#### Modulo

In [ ]:
result_mod = arr_list2 % arr_list1

#### Floor Division

In [29]:
result_floor = arr_list2 // arr_list1

result_floor

array([2, 2, 2, 2, 2])

#### Numpy Subsetting

In [30]:
# result3 <= 800
print(result_mul <= 800)
print(result_mul[result_mul <= 800])

# test_ndStrings = np.array(['Bob','Mark','Angelica','Barb'])
# print(test_ndStrings[test_ndStrings[0] == 'B'])

# conditioal check, returns true or false
# print(arr1 < 2)
# print(arr2 >= 2)

# conditional check, that returns the elements that meet the given condition


NameError: name 'result_mul' is not defined

In [31]:
print(result_prod)
print(result_prod > 500)

[  50  200  450  800 1250]
[False False False  True  True]


In [32]:
#subset an array with a conditional. this will only return the matching value 
result_prod[result_prod > 500]

array([ 800, 1250])

In [35]:
test_ndStrings = np.array(['Bob','Mark','Angelica','Barb'])
print(test_ndStrings)
print(test_ndStrings[0] == 'B')
print(test_ndStrings[0])


['Bob' 'Mark' 'Angelica' 'Barb']
False
Bob


#### Multi-dimensional Arrays <br>
<p>NumPy seamlessly supports multidimensional arrays and matrices of arbitrary dimension without nesting NDArrays. NDArrays themselves are flexible and extensible and may be defined with such dimensions, with a rich API of common functions to facilitate their use. Let's start by building a two dimensional 3x3 matrix by conversion from a nested group of core python lists $M = [l_0, l_1, l_2]$:</p>

In [37]:
aList = [0,1,2]
bList = [3,4,5]
cList = [6,7,8]

# first step: convert lists into a Matrix
M = [aList, bList,cList]
print(M[1]) # this will give us our bList
print(M[1][1]) #this will return the 1 index of bList

# second step: place Matrix inside NDArray
ND_M = np.array(M)
print (f"MDArray Structure: \n{ND_M}")

ND_M



[3, 4, 5]
4
MDArray Structure: 
[[0 1 2]
 [3 4 5]
 [6 7 8]]


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### Indexing NDArrays <br>
<p> Similar to lists within lists; however, the syntax looks more like C programming language.... It is [1, 2] to access the second row, third element.</p>

In [38]:
print(ND_M[1,1])

4


#### Assigning Values in NDArrays

In [39]:
ND_M[1,1] = 44

ND_M


array([[ 0,  1,  2],
       [ 3, 44,  5],
       [ 6,  7,  8]])

<p>Notice above how we ended up with a 1 in the target element's place. This is a data type issue. The .dtype() method is supported by all NDArrays, as well as the .astype() method for casting between data types:</p>

#### Checking NDArray Type

In [40]:
# usind the .dtype() method
ND_M.dtype 


dtype('int64')

#### Altering NDArray Type

In [42]:
print(ND_M.dtype)

changed = ND_M.astype(np.float32)

print(changed.dtype)
print(changed)

int64
float32
[[ 0.  1.  2.]
 [ 3. 44.  5.]
 [ 6.  7.  8.]]


#### Checking the Shape <br>
<p>The behavior and properties of an NDArray are often sensitively dependent on the $\textit{shape}$ of the NDArray itself. The shape of an array can be found by calling the .shape method, which will return a tuple containing the array's dimensions:</p>

In [44]:
# Checking the Shape of the ND_M Numpy Array
# Using the method .shape

ND_M.shape

(3, 3)

In [ ]:

 # shape is always rows x columns
# Checking the Shape of the ND_M Numpy Array
# Using the method .shape

#### Altering the Shape <br>
<p>As long as the number of elements remains fixed, we can reshape NDArrays at will:</p>

In [45]:
# Change the shape of the numpy array
# Using the method .reshape()

# The reshape should be a multiple of the original shape
# Meaning we can have a shape of (1,9) or (9,1) or (3,3)

# (9,1) == 9 rows , 1 column

reshaped = ND_M.reshape((9,1))

reshaped



array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [44],
       [ 5],
       [ 6],
       [ 7],
       [ 8]])

In [46]:
# keep in mind that the shape numbers do matter, (9, 1) is different than (1, 9)
reshaped2 = ND_M.reshape((1,9))

reshaped2

array([[ 0,  1,  2,  3, 44,  5,  6,  7,  8]])

#### In-Class Exercise #2 - Create a matrix of range 0 up to 16 and reshape it into a 4x4 matrice

In [49]:

array_range= np.arange(0,16,1)
array_range

new_array = array_range.reshape((4,4))
new_array


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

#### Complex Indexing & Assinging

In [55]:

print('Setting the Matrix')
M = np.zeros((6,6 ))
print('Before Assignment')
print(M)
#set the first column to equal 1
M[:,0] = 1 
print('After Assigning 1 to First Column')
print(M)


Setting the Matrix
Before Assignment
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
After Assigning 1 to First Column
[[1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]]


#### Elementwise Multiplication

<p>As long as the shapes of NDArrays are 'compatible', they can be multiplied elementwise, broadcasted, used in inner products, and much much more. 'Compatible' in this context can mean compatible in the linear algebraic sense, i.e. for inner products and other matrix multiplication, or simply sharing a dimension in such a manner that broadcasting 'makes sense'. Here are some examples of this:</p>

In [ ]:
arr1 = np.arange(9).reshape((3,3))
print(arr1)

arr2 = np.array([5,10,15])
print(arr2)


#### np.where() <br>
<p>If statement within NDArrays that allows you to run conditionals on the entire array</p>

#### Random Sampling <br>
<p>NumPy provides machinery to work with random numbers - something often needed in a broad spectrum of data science applications.</p>

In [102]:
# np.random.uniform()

# A single call generates a single random number between 0 and 1

print('Here is a random number: %s' % np.random.uniform())

# You can also pass some parameters or bounds

print('Here is a random number between 0 and 1 Million: %s' % np.random.uniform(0, 1e6))

# You can also generate a bunch of random numbers all at once

print('Here are 5 random numbers between 0 and 10: %s' % np.random.uniform(0, 10, 5))

# Even matrices with shapes as a parameter

print('Here is a 3x3 matrix with numbers between 0 and 10: \n %s' % np.random.uniform(0, 10, (3, 3)))

Here is a random number: 0.4492129324117191
Here is a random number between 0 and 1 Million: 448355.3328268317
Here are 5 random numbers between 0 and 10: [4.34985199 6.61371212 2.02942425 6.45644686 7.64140448]
Here is a 3x3 matrix with numbers between 0 and 10: 
 [[5.80549309 3.79206995 6.12907764]
 [8.63809959 7.82531962 6.46201148]
 [0.10362886 6.84349173 7.06132243]]


## Working With CSV's

#### Imports

In [108]:
import csv


#### Reading a CSV

In [106]:
# Creating Function to open and read CSV data
def open_csv (filename, d=','):
    data=[]
    
    #open the file
    with open(filename) as marathon_data:
        #read the file with the csv reader -> Reader object
        marathon_reader = csv.reader(marathon_data, delimiter= d)
        
        #loop over the reader and append each row to the data list
        for row in marathon_reader:
            data.append(row)
    #return the data list after the file has been closed
    return data


In [107]:
marathon17 = open_csv('./boston_marathon2017_edited.csv')

print(marathon17[:5])

FileNotFoundError: [Errno 2] No such file or directory: './boston_marathon2017_edited.csv'

#### Loading a CSV's Data 

In [ ]:
FIELDS = ['Rk', 'Pos', 'Name', 'Age', 'G', 'PA', 'AB', 'R', 'H', '2B', '3B', 'HR', 'RBI', 'SB', 'CS', 
          'BB', 'SO', 'BA', 'OBP', 'SLG', 'OPS', 'OPS+', 'TB', 'GDP', 'HBP', 'SH', 'SF', 'IBB']

DATATYPES = [('rk', 'i'), ('pos', '|S25'), ('name', '|S25'), ('age', 'i'), ('g', 'i'), ('pa', 'i'), ('ab', 'i'),
                ('r', 'i'), ('h', 'i'), ('2b', 'i'), ('3b', 'i'), ('hr', 'i'), ('rbi', 'i'), ('sb', 'i'), ('cs', 'i'),
                ('bb', 'i'), ('so', 'i'), ('ba', 'f'), ('obp', 'f'), ('slg', 'f'), ('ops', 'f'), ('opsp', 'i'),
                ('tb', 'i'), ('gdp', 'i'), ('hbp', 'i'), ('sh', 'i'), ('sf', 'i'), ('ibb', 'i')]



# instead of loading csv normally, let's load it into a numpy array to calculate results on

def np_read_csv(filename, d=','):
    data = np.genfromtxt(filename, delimiter=d, names = True, dtype = DATATYPES)
    return data

bs17 = np_read_csv()


#### Summing the top 5 hitters for HR's

In [ ]:
# find the top 5 hr hitters
# Step 1: Get all HR data into a variable
# Step 2: Get all the player names into a variable
# Step 3: Create a new empty list for decoded names
# Step 4: Loop through and decode each name and append to new list
# Step 5: Line up our player names with our hr data [(player, number_of_hr), (player2, number_of_hr),...]
# Step 6: Sort values based on number of home runs
# Step 7: Slice list to first 5

#step 1:
all_home_runs = bs17['HR']
print(all_home_runs)

#step 2
all_players = bs17['Name']

#step3
clean_names =[]

#step4
for name in all_players:
    decoded_names = name.decode('utf-8')
    clean_names.append(swcoded_names)

#step 5:
 zipped_values [(clean_names[i], all_home_runs[i]) for i in range(len(clean_names))]
    
#step6:
sorted_hrs= sorted
    


# Exercises To Complete.... <br>
<p>Given in separate file after completion of this file</p>